<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->getLocale() === 'ar' ? 'rtl' : 'ltr' }}">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ data_get($landingPage->settings, app()->getLocale() === 'ar' ? 'seo_title_ar' : 'seo_title_en') ?: $landingPage->translations->firstWhere('locale', app()->getLocale())?->title ?? $landingPage->slug }}</title>
    @if($landingPage->account?->favicon_path)<link rel="icon" href="{{ Storage::disk('public')->url($landingPage->account->favicon_path) }}">@endif
    @php($seoDescription = data_get($landingPage->settings, app()->getLocale() === 'ar' ? 'seo_description_ar' : 'seo_description_en') ?: $landingPage->translations->firstWhere('locale', app()->getLocale())?->description)
    @if($seoDescription)<meta name="description" content="{{ $seoDescription }}">@endif
    @if($keywords = data_get($landingPage->settings, 'seo_keywords'))<meta name="keywords" content="{{ $keywords }}">@endif
    @if($canonical = data_get($landingPage->settings, 'canonical_url'))<link rel="canonical" href="{{ $canonical }}">@endif
    @if(data_get($landingPage->settings, 'seo_noindex'))<meta name="robots" content="noindex,nofollow">@endif
    @if($ogImage = data_get($landingPage->settings, 'seo_og_image'))<meta property="og:image" content="{{ Storage::url($ogImage) }}">@endif
    @php($design = $landingPage->settings ?? [])
    @php($fontStacks = ['cairo' => 'Cairo, Tahoma, sans-serif', 'tajawal' => 'Tajawal, Tahoma, sans-serif', 'inter' => 'Inter, Arial, sans-serif', 'noto' => 'Noto Sans Arabic, Tahoma, sans-serif'])
    @php($font = $fontStacks[$design['font_family'] ?? 'cairo'] ?? $fontStacks['cairo'])
    @php($headingSize = max(24, min(72, (int) ($design['heading_size'] ?? 44))))
    @php($bodySize = max(14, min(24, (int) ($design['body_size'] ?? 18))))
    @php($primaryColor = preg_match('/^#[0-9a-fA-F]{6}$/', (string) ($design['primary_color'] ?? '')) ? $design['primary_color'] : '#4f46e5')
    @php($currentPriceColor = preg_match('/^#[0-9a-fA-F]{6}$/', (string) ($design['current_price_color'] ?? '')) ? $design['current_price_color'] : $primaryColor)
    @php($comparePriceColor = preg_match('/^#[0-9a-fA-F]{6}$/', (string) ($design['compare_price_color'] ?? '')) ? $design['compare_price_color'] : '#98a2b3')
    @php($currentPriceSize = max(20, min(64, (int) ($design['current_price_size'] ?? 32))))
    @php($comparePriceSize = max(14, min(36, (int) ($design['compare_price_size'] ?? 20))))
    <style>
        :root{--brand:{{ $primaryColor }};--ink:#172033;--muted:#667085;--surface:#f7f8fc;--current-price:{{ $currentPriceColor }};--compare-price:{{ $comparePriceColor }}}*{box-sizing:border-box}body{margin:0;background:var(--surface);color:var(--ink);font-family:{{ $font }};font-size:{{ $bodySize }}px}.shell{max-width:920px;margin:0 auto;padding:24px 16px 64px}.hero,.card{background:#fff;border-radius:24px;box-shadow:0 18px 50px #17203312;overflow:hidden}.hero{text-align:center;padding:44px 24px 28px}h1{margin:0 0 12px;font-size:clamp(28px,5vw,{{ $headingSize }}px)}.description{color:var(--muted);font-size:1em}.product-image{display:block;width:100%;max-height:520px;object-fit:contain;margin:24px auto 0;border-radius:16px}.card{margin-top:20px;padding:28px}.card h2{margin-top:0}form{display:grid;gap:16px}label{display:grid;gap:7px;font-weight:700}input{width:100%;border:1px solid #d0d5dd;border-radius:12px;padding:14px;font:inherit}button{border:0;border-radius:12px;padding:15px 22px;background:var(--brand);color:#fff;font:inherit;font-weight:800;cursor:pointer}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.switch{text-align:end;margin-bottom:14px}.switch a{color:var(--brand);text-decoration:none;font-weight:700}@media(max-width:640px){.grid{grid-template-columns:1fr}.hero,.card{border-radius:16px}}
        .price{display:flex;justify-content:center;gap:34px;align-items:flex-start;margin:24px 0}.price-item{text-align:center;display:grid;gap:8px}.price-label{font-size:14px;font-weight:800}.current-label{color:var(--current-price)}.old-label{color:#dc2626}.current{color:var(--current-price);font-size:{{ $currentPriceSize }}px;font-weight:800}.old{color:var(--compare-price);text-decoration:line-through;font-size:{{ $comparePriceSize }}px;font-weight:700}
        .section{margin-top:20px;background:#fff;border-radius:20px;padding:28px;box-shadow:0 18px 50px #17203312}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.feature{padding:16px;border:1px solid #eaecf0;border-radius:14px}.countdown{text-align:center;background:#fff;color:var(--ink)}.countdown-grid{display:grid;grid-template-columns:repeat(4, minmax(70px, 110px));justify-content:center;gap:14px;margin-top:18px}.countdown-box{border-radius:16px;background:#f8fafc;padding:14px 10px;border:1px solid #eaecf0}.countdown-value{display:block;font-size:32px;font-weight:900;color:var(--countdown-color,#8a9b22);line-height:1}.countdown-label{display:block;margin-top:8px;font-size:14px;font-weight:700;color:var(--countdown-label-color,#667085)}.wa{display:inline-block;background:#16a34a;color:#fff;padding:12px 18px;border-radius:999px;text-decoration:none}@media(max-width:640px){.features{grid-template-columns:1fr}.countdown-grid{gap:8px}.countdown-value{font-size:26px}}
        .reviews{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.review{border:1px solid #eaecf0;border-radius:14px;padding:18px}.stars{color:#f59e0b;letter-spacing:2px}.review p{color:var(--muted);line-height:1.8}@media(max-width:640px){.reviews{grid-template-columns:1fr}}
        .gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.gallery img{width:100%;height:220px;object-fit:cover;border-radius:14px}.video-link{display:inline-flex;padding:14px 20px;border-radius:12px;background:var(--brand);color:#fff;text-decoration:none;font-weight:800}@media(max-width:640px){.gallery{grid-template-columns:1fr}.gallery img{height:240px}}
        .slider{padding:0;position:relative}.slider-track{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none}.slider-track::-webkit-scrollbar{display:none}.slider-track img{display:block;flex:0 0 100%;width:100%;height:360px;object-fit:cover;scroll-snap-align:start}.slider-dots{display:none}.social-grid{display:flex;flex-wrap:wrap;gap:12px}.social-grid a{background:var(--social-color);color:#fff;text-decoration:none;padding:12px 18px;border-radius:999px;font-weight:800}
        .fieldset{border:0;padding:0;margin:0;display:grid;gap:8px}.field-options{display:grid;gap:8px}.field-options label{display:flex;align-items:center;gap:8px;font-weight:600}.field-options input{width:auto}
    </style>
    <link rel="stylesheet" href="{{ asset('css/landing-page.css') }}">
</head>
<body>{!! data_get($landingPage->settings, 'body_code') !!}<main class="shell">
    <div class="switch"><a href="{{ route('locale.switch', app()->getLocale() === 'ar' ? 'en' : 'ar') }}"><img src="{{ asset(app()->getLocale() === 'ar' ? 'images/flags/gb.png' : 'images/flags/ae.png') }}" alt="{{ app()->getLocale() === 'ar' ? 'English' : 'العربية' }}"> <span>{{ app()->getLocale() === 'ar' ? 'English' : 'العربية' }}</span></a></div>
    @php($pageTranslation = $landingPage->translations->firstWhere('locale', app()->getLocale()) ?? $landingPage->translations->first())
    @php($product = $landingPage->product)
    @php($productTranslation = $product?->translations->firstWhere('locale', app()->getLocale()) ?? $product?->translations->first())
    @php($orderSection = $landingPage->sections->firstWhere('type.value', 'order_form'))
    @php($showOrderForm = (bool) data_get($landingPage->settings, 'show_order_form', true) && (!$orderSection || $orderSection->is_visible))
    @php($orderTitle = data_get($landingPage->settings, app()->getLocale() === 'ar' ? 'order_form_title_ar' : 'order_form_title_en') ?: (data_get($landingPage->settings, 'order_form_title') ?: data_get($orderSection?->settings, 'title') ?: __('landivo.public.order_title')))
    @php($formFields = collect(data_get($landingPage->settings, 'order_form_fields', [])))
    @if($formFields->isEmpty()) @php($formFields = collect(data_get($orderSection?->settings, 'fields', []))) @endif
    @php($currentLocale = app()->getLocale())
    @php($formFields = $formFields->filter(fn ($field) => ($field['is_active'] ?? true) && filled($field['internal_name'] ?? $field['key'] ?? null) && !($currentLocale === 'ar' ? str_ends_with((string) ($field['internal_name'] ?? $field['key']), '_en') : str_ends_with((string) ($field['internal_name'] ?? $field['key']), '_ar')))->sortBy('sort_order')->values())
    @php($fieldKeys = $formFields->map(fn ($field) => $field['internal_name'] ?? $field['key'])->all())
    @php($hasDynamicName = (bool) array_intersect($fieldKeys, ['name', 'full_name_ar', 'full_name_en']))
    @php($hasDynamicPhone = in_array('phone', $fieldKeys, true))
    @php($hasDynamicCity = (bool) array_intersect($fieldKeys, ['city', 'emirate']))
    @php($hasDynamicQuantity = in_array('quantity', $fieldKeys, true))
    @php($showLegacyQuantity = $formFields->isEmpty())
    @php($sectionOrder = collect(data_get($landingPage->settings, 'section_order', []))->pluck('type')->filter()->values())
    @php($sectionPosition = fn (string $type, int $fallback): int => ($position = $sectionOrder->search($type)) === false ? $fallback : $position)
    <section class="hero" style="order:{{ $sectionPosition('hero', 0) }}"><h1>{{ $pageTranslation?->title ?? $productTranslation?->name ?? $landingPage->slug }}</h1>
        @if($pageTranslation?->description)<p class="description">{{ $pageTranslation->description }}</p>@endif
        @php($localizedProductImage = data_get($landingPage->settings, app()->getLocale() === 'ar' ? 'product_image_ar' : 'product_image_en') ?: data_get($product?->metadata, app()->getLocale() === 'ar' ? 'image_ar' : 'image_en') ?: $product?->primary_image_path)
        @if($localizedProductImage)<img class="product-image" src="{{ Storage::url($localizedProductImage) }}" alt="{{ $productTranslation?->name }}">@endif
        @if($product)<div class="price"><div class="price-item"><span class="price-label current-label">{{ __('landivo.public.price_after_discount') }}</span><span class="current">{{ number_format((float)$product->price,2) }} {{ $product->currency }}</span></div>@if($product->compare_at_price)<div class="price-item"><span class="price-label old-label">{{ __('landivo.public.price_before_discount') }}</span><span class="old">{{ number_format((float)$product->compare_at_price,2) }} {{ $product->currency }}</span></div>@endif</div>@endif
    </section>
    @if(!empty(data_get($landingPage->settings, 'slider_images')))
        <section class="section slider" style="order:{{ $sectionPosition('product_gallery', 10) }}" data-slider data-interval="{{ (int) data_get($landingPage->settings, 'slider_interval', 4000) }}"><div class="slider-track">@foreach((array) data_get($landingPage->settings, 'slider_images', []) as $slide)<img src="{{ Storage::url($slide) }}" alt="{{ $pageTranslation?->title ?? $landingPage->slug }}">@endforeach</div><div class="slider-dots"></div></section>
    @endif
    @php($galleryImages = data_get($landingPage->settings, app()->getLocale() === 'ar' ? 'gallery_images_ar' : 'gallery_images_en') ?: data_get($landingPage->settings, 'gallery_images', []))
    @php($showcaseSettings = (array) data_get($landingPage->settings, 'product_showcase', []))
    @if(($showcaseSettings['enabled'] ?? false) && $showcaseProducts->isNotEmpty())
        @php($showcaseTitle = app()->getLocale() === 'ar' ? ($showcaseSettings['title_ar'] ?? 'منتجاتنا') : ($showcaseSettings['title_en'] ?? 'Our Products'))
        @php($showcaseLayout = $showcaseSettings['layout'] ?? 'grid')
        <section class="section product-showcase product-showcase-{{ $showcaseLayout }}" style="order:{{ $sectionPosition('product_showcase', 15) }}" @if($showcaseLayout === 'slider') data-product-slider @endif><h2>{{ $showcaseTitle }}</h2><div class="product-showcase-grid">@foreach($showcaseProducts as $showcaseProduct) @php($showcaseTranslation = $showcaseProduct->translations->firstWhere('locale', app()->getLocale()) ?: $showcaseProduct->translations->first()) @php($showcaseImage = data_get($showcaseProduct->metadata, app()->getLocale() === 'ar' ? 'image_ar' : 'image_en') ?: $showcaseProduct->primary_image_path) @php($showcaseDiscount = $showcaseProduct->compare_at_price && $showcaseProduct->compare_at_price > $showcaseProduct->price ? round((1 - ($showcaseProduct->price / $showcaseProduct->compare_at_price)) * 100) : 0)<article class="product-card"><div class="product-card-image">@if($showcaseImage)<img src="{{ Storage::url($showcaseImage) }}" alt="{{ $showcaseTranslation?->name }}">@endif @if(($showcaseSettings['show_discount'] ?? true) && $showcaseDiscount > 0)<span class="product-discount">-{{ $showcaseDiscount }}%</span>@endif</div><div class="product-card-body"><h3>{{ $showcaseTranslation?->name ?? $showcaseProduct->sku }}</h3>@if($showcaseSettings['show_price'] ?? true)<div class="product-card-price"><strong>{{ number_format((float) $showcaseProduct->price, 2) }} {{ $showcaseProduct->currency }}</strong>@if($showcaseProduct->compare_at_price && $showcaseProduct->compare_at_price > $showcaseProduct->price)<del>{{ number_format((float) $showcaseProduct->compare_at_price, 2) }} {{ $showcaseProduct->currency }}</del>@endif</div>@endif<a class="product-card-button" href="#order-form">{{ app()->getLocale() === 'ar' ? 'اطلب الآن' : 'Order now' }}</a></div></article>@endforeach</div></section>@if($showcaseLayout === 'slider')<script>document.querySelectorAll('[data-product-slider]').forEach(function(section){var track=section.querySelector('.product-showcase-grid');if(!track||track.children.length<2||!{{ ($showcaseSettings['autoplay'] ?? true) ? 'true' : 'false' }})return;setInterval(function(){var card=track.children[0],step=card.offsetWidth+16;if(track.scrollLeft+track.clientWidth>=track.scrollWidth-4)track.scrollTo({left:0,behavior:'smooth'});else track.scrollBy({left:step,behavior:'smooth'})},4000)});</script>@endif
    @endif
    @if(!empty($galleryImages))
        <section class="gallery-section" style="order:{{ $sectionPosition('gallery', 20) }}"><div class="gallery-stack">@foreach((array) $galleryImages as $image)<img src="{{ Storage::url($image) }}" alt="{{ $pageTranslation?->title ?? $landingPage->slug }}">@endforeach</div></section>
    @endif
    @if(!empty(data_get($landingPage->settings, 'video_url')))
        <section class="section" style="order:{{ $sectionPosition('video', 30) }}"><h2>{{ __('landivo.sections.video') }}</h2><a class="video-link" href="{{ data_get($landingPage->settings, 'video_url') }}" target="_blank" rel="noopener">{{ data_get($landingPage->settings, 'video_label') ?: __('landivo.sections.video') }}</a></section>
    @endif
    @if((bool) data_get($landingPage->settings, 'show_countdown') && filled(data_get($landingPage->settings, 'countdown_ends_at')))
        @php($countdownColor = preg_match('/^#[0-9a-fA-F]{6}$/', (string) data_get($landingPage->settings, 'countdown_color')) ? data_get($landingPage->settings, 'countdown_color') : '#8a9b22')
        @php($countdownLabelColor = preg_match('/^#[0-9a-fA-F]{6}$/', (string) data_get($landingPage->settings, 'countdown_label_color')) ? data_get($landingPage->settings, 'countdown_label_color') : '#667085')
        @php($countdownTitle = app()->getLocale() === 'ar' ? data_get($landingPage->settings, 'countdown_title_ar') : data_get($landingPage->settings, 'countdown_title_en'))
        <section class="section countdown" style="order:{{ $sectionPosition('countdown', 35) }};--countdown-color:{{ $countdownColor }};--countdown-label-color:{{ $countdownLabelColor }}"><h2>{{ $countdownTitle }}</h2><div class="countdown-grid" data-countdown="{{ data_get($landingPage->settings, 'countdown_ends_at') }}"><div class="countdown-box"><span class="countdown-value" data-unit="days">00</span><span class="countdown-label">{{ app()->getLocale() === 'ar' ? 'يوم' : 'Days' }}</span></div><div class="countdown-box"><span class="countdown-value" data-unit="hours">00</span><span class="countdown-label">{{ app()->getLocale() === 'ar' ? 'ساعة' : 'Hours' }}</span></div><div class="countdown-box"><span class="countdown-value" data-unit="minutes">00</span><span class="countdown-label">{{ app()->getLocale() === 'ar' ? 'دقيقة' : 'Minutes' }}</span></div><div class="countdown-box"><span class="countdown-value" data-unit="seconds">00</span><span class="countdown-label">{{ app()->getLocale() === 'ar' ? 'ثانية' : 'Seconds' }}</span></div></div></section>
    @endif
    @php($orderedSections = $sectionOrder->isEmpty() ? $landingPage->sections : $landingPage->sections->sortBy(fn ($section) => ($position = $sectionOrder->search($section->type->value)) === false ? 9999 : $position)->values())
    @foreach($orderedSections as $section)
        @continue(!$section->is_visible)
        @php($settings = $section->settings ?? [])
        @php($settings['title'] = data_get($settings, app()->getLocale() === 'ar' ? 'title_ar' : 'title_en') ?: ($settings['title'] ?? null))
        @php($settings['subtitle'] = data_get($settings, app()->getLocale() === 'ar' ? 'subtitle_ar' : 'subtitle_en') ?: ($settings['subtitle'] ?? null))
        @php($settings['label'] = data_get($settings, app()->getLocale() === 'ar' ? 'label_ar' : 'label_en') ?: ($settings['label'] ?? null))
        <div class="landing-section" style="order:{{ $sectionPosition($section->type->value, 40) }}">
        @switch($section->type->value)
            @case('features')
                <section class="section"><h2>{{ $settings['title'] ?? __('landivo.sections.features') }}</h2><div class="features">@foreach(collect($settings)->filter(fn ($value, $key) => str_starts_with((string) $key, 'item_')) as $feature)<div class="feature">{{ $feature }}</div>@endforeach</div></section>
                @break
            @case('countdown')
                @php($countdownColor = preg_match('/^#[0-9a-fA-F]{6}$/', (string) ($settings['countdown_color'] ?? '')) ? $settings['countdown_color'] : '#8a9b22')
                @php($countdownLabelColor = preg_match('/^#[0-9a-fA-F]{6}$/', (string) ($settings['countdown_label_color'] ?? '')) ? $settings['countdown_label_color'] : '#667085')
                <section class="section countdown" style="--countdown-color:{{ $countdownColor }};--countdown-label-color:{{ $countdownLabelColor }}"><h2>{{ $settings['title'] ?? __('landivo.sections.countdown') }}</h2><div class="countdown-grid" data-countdown="{{ $settings['ends_at'] ?? '' }}"><div class="countdown-box"><span class="countdown-value" data-unit="days">00</span><span class="countdown-label">{{ app()->getLocale() === 'ar' ? 'يوم' : 'Days' }}</span></div><div class="countdown-box"><span class="countdown-value" data-unit="hours">00</span><span class="countdown-label">{{ app()->getLocale() === 'ar' ? 'ساعة' : 'Hours' }}</span></div><div class="countdown-box"><span class="countdown-value" data-unit="minutes">00</span><span class="countdown-label">{{ app()->getLocale() === 'ar' ? 'دقيقة' : 'Minutes' }}</span></div><div class="countdown-box"><span class="countdown-value" data-unit="seconds">00</span><span class="countdown-label">{{ app()->getLocale() === 'ar' ? 'ثانية' : 'Seconds' }}</span></div></div></section>
                @break
            @case('gallery')
            @case('product_gallery')
                @if(!empty($settings['images']))<section class="gallery-section"><div class="gallery-stack">@foreach((array) $settings['images'] as $image)<img src="{{ Storage::url($image) }}" alt="{{ $pageTranslation?->title ?? $landingPage->slug }}">@endforeach</div></section>@endif
                @break
            @case('video')
                @if(!empty($settings['video_url']))<section class="section"><h2>{{ $settings['title'] ?? __('landivo.sections.video') }}</h2><a class="video-link" href="{{ $settings['video_url'] }}" target="_blank" rel="noopener">{{ $settings['label'] ?? __('landivo.editor.video_url') }}</a></section>@endif
                @break
            @case('testimonials')
                @if($landingPage->reviews->isNotEmpty())<section class="section"><h2>{{ $settings['title'] ?? __('landivo.sections.testimonials') }}</h2><div class="reviews">@foreach($landingPage->reviews as $review)<article class="review"><strong>{{ $review->name }}</strong><div class="stars">{{ str_repeat('★', $review->rating) }}{{ str_repeat('☆', 5 - $review->rating) }}</div><p>{{ strip_tags($review->content) }}</p></article>@endforeach</div></section>@endif
                @break
            @case('whatsapp')
                @if(!empty($settings['number']))<section class="section" style="text-align:center"><a class="wa" href="https://wa.me/{{ preg_replace('/\D+/', '', $settings['number']) }}" target="_blank">{{ $settings['label'] ?? __('landivo.sections.whatsapp') }}</a></section>@endif
                @break
        @endswitch
        </div>
    @endforeach
    @php($socialStyle = data_get($landingPage->settings, 'social_icon_style', 'circle'))
    @php($socialSize = max(32, min(80, (int) data_get($landingPage->settings, 'social_icon_size', 54))))
    @php($socialGap = max(4, min(40, (int) data_get($landingPage->settings, 'social_icon_gap', 14))))
    <style>.social-section{margin-bottom:{{ max(18, (int) data_get($landingPage->settings, 'footer_spacing', 28)) }}px}.social-grid{gap:{{ $socialGap }}px}.social-icon{width:{{ $socialStyle === 'pill' ? 'auto' : $socialSize.'px' }};height:{{ $socialStyle === 'pill' ? '46px' : $socialSize.'px' }};padding:{{ $socialStyle === 'pill' ? '0 18px' : '0' }};border-radius:{{ in_array($socialStyle, ['circle','soft','glass'], true) ? '50%' : ($socialStyle === 'pill' ? '999px' : '16px') }};{{ $socialStyle === 'outline' ? 'background:transparent!important;border:2px solid var(--social-color);color:var(--social-color);' : '' }}{{ $socialStyle === 'soft' ? 'background:color-mix(in srgb,var(--social-color) 14%,#fff)!important;color:var(--social-color);' : '' }}{{ $socialStyle === 'glass' ? 'background:color-mix(in srgb,var(--social-color) 70%,transparent)!important;backdrop-filter:blur(10px);border:1px solid #ffffff80;' : '' }}</style>
    @if(!empty(data_get($landingPage->settings, 'social_media')))
        <section class="social-section" style="order:{{ $sectionPosition('social_media', 50) }}" aria-label="{{ __('landivo.sections.social_media') }}"><div class="social-grid">@foreach((array) data_get($landingPage->settings, 'social_media', []) as $social) @if($social['is_active'] ?? true)<a class="social-icon social-{{ $social['platform'] ?? 'social' }}" href="{{ $social['url'] ?? '#' }}" target="_blank" rel="noopener" aria-label="{{ ucfirst($social['platform'] ?? 'Social') }}" style="--social-color:{{ $social['color'] ?? '#4f46e5' }}">@switch($social['platform'] ?? '') @case('instagram')<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" class="fill"/></svg>@break @case('facebook')<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 8h3V4h-3c-3 0-5 2-5 5v3H6v4h3v4h4v-4h3l1-4h-4V9c0-.7.3-1 1-1Z"/></svg>@break @case('youtube')<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 7.5a2.8 2.8 0 0 0-2-2C17.3 5 12 5 12 5s-5.3 0-7 .5a2.8 2.8 0 0 0-2 2A29 29 0 0 0 2.5 12 29 29 0 0 0 3 16.5a2.8 2.8 0 0 0 2 2c1.7.5 7 .5 7 .5s5.3 0 7-.5a2.8 2.8 0 0 0 2-2 29 29 0 0 0 .5-4.5 29 29 0 0 0-.5-4.5ZM10 15.5v-7l6 3.5-6 3.5Z"/></svg>@break @case('tiktok')<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 4h3c.3 1.7 1.3 2.8 3 3v3c-1.2 0-2.3-.3-3-.8V15a5 5 0 1 1-5-5v3a2 2 0 1 0 2 2V4Z"/></svg>@break @case('whatsapp')<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3a8.8 8.8 0 0 0-7.6 13.4L3 21l4.8-1.3A8.8 8.8 0 1 0 12 3Zm4.7 12.6c-.2.5-1 .9-1.4.9-.4.1-.9.1-1.5-.1a12.4 12.4 0 0 1-1.4-.5 10.8 10.8 0 0 1-4.2-4.1c-.3-.5-.6-1.1-.6-1.7s.3-1.1.6-1.4c.2-.2.4-.3.6-.3h.4c.2 0 .3.1.4.4l.6 1.5c.1.2.1.4 0 .6l-.3.4c-.1.2-.2.3-.1.5.3.6.8 1.1 1.3 1.5.5.4 1.1.7 1.7.9.2.1.4 0 .5-.1l.6-.7c.1-.2.3-.2.5-.1l1.5.7c.2.1.3.2.3.5Z"/></svg>@break @default<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M8 12h8M12 8v8"/></svg>@endswitch</a>@endif @endforeach</div></section>
    @endif
    @php($formTitleAlignment = data_get($landingPage->settings, app()->getLocale() === 'ar' ? 'order_form_title_alignment_ar' : 'order_form_title_alignment_en', 'start'))
    @php($formLabelAlignment = data_get($landingPage->settings, app()->getLocale() === 'ar' ? 'order_form_label_alignment_ar' : 'order_form_label_alignment_en', 'start'))
    @if($showOrderForm)<section id="order-form" class="card order-form-card" style="order:{{ $sectionPosition('order_form', 60) }};--form-title-align:{{ $formTitleAlignment }};--form-label-align:{{ $formLabelAlignment }}"><h2>{{ $orderTitle }}</h2><form dir="{{ app()->getLocale() === 'ar' ? 'rtl' : 'ltr' }}" method="POST" enctype="multipart/form-data" action="{{ route('landing-pages.submit',$landingPage->slug) }}">@csrf
        @if(!$hasDynamicName && !$hasDynamicPhone)<div class="grid"><label>{{ __('landivo.public.name') }}<input name="name" value="{{ old('name') }}" required></label><label>{{ __('landivo.public.phone') }}<input name="phone" value="{{ old('phone') }}" required></label></div>@elseif(!$hasDynamicName)<label>{{ __('landivo.public.name') }}<input name="name" value="{{ old('name') }}" required></label>@elseif(!$hasDynamicPhone)<label>{{ __('landivo.public.phone') }}<input name="phone" value="{{ old('phone') }}" required></label>@endif
        @if($showLegacyQuantity || !$hasDynamicCity)<div class="grid">@if($showLegacyQuantity)<label>{{ __('landivo.public.quantity') }}<input type="number" min="1" max="100" name="quantity" value="1"></label>@endif @if(!$hasDynamicCity)<label>{{ __('landivo.public.city') }}<input name="city" value="{{ old('city') }}"></label>@endif</div>@endif
        @foreach($formFields as $field)
            @php($fieldKey = $field['internal_name'] ?? $field['key'])
            @php($fieldType = $field['type'] ?? 'text')
            @php($fieldOptions = collect(preg_split('/\r\n|\r|\n/', (string) ($currentLocale === 'en' && filled($field['options_en'] ?? null) ? $field['options_en'] : ($field['options'] ?? ''))))->map(fn ($option) => trim($option))->filter()->values())
            @php($fieldTranslation = collect($field['translations'] ?? [])->firstWhere('locale', app()->getLocale()))
            @php($fieldLabel = $fieldTranslation['label'] ?? ($field['label'] ?? $fieldKey))
            @php($fieldPlaceholder = $fieldTranslation['placeholder'] ?? ($field['placeholder'] ?? ''))
            @php($fieldRequired = !empty($field['required']))
            @php($fieldConditions = e(json_encode($field['conditions'] ?? [])))
            @if($fieldType === 'hidden')
                <input type="hidden" name="custom[{{ $fieldKey }}]" value="{{ $field['default_value'] ?? '' }}">
            @elseif($fieldType === 'textarea' || $fieldType === 'address')
                <label data-form-field="{{ $fieldKey }}">{{ $fieldLabel }} @if($fieldRequired)<span class="required-mark">{{ app()->getLocale() === 'ar' ? 'مطلوب' : 'Required' }}</span>@endif<textarea name="custom[{{ $fieldKey }}]" rows="4" placeholder="{{ $fieldPlaceholder }}" @required($fieldRequired)>{{ old('custom.'.$fieldKey, $field['default_value'] ?? '') }}</textarea></label>
            @elseif(in_array($fieldType, ['select', 'product_variant', 'country'], true))
                <label data-form-field="{{ $fieldKey }}">{{ $fieldLabel }} @if($fieldRequired)<span>*</span>@endif<select name="custom[{{ $fieldKey }}]" @required($fieldRequired)><option value="">{{ $fieldPlaceholder ?: (app()->getLocale() === 'ar' ? 'اختر خيارًا' : 'Choose an option') }}</option>@foreach($fieldOptions as $option)<option value="{{ $option }}" @selected(old('custom.'.$fieldKey, $field['default_value'] ?? '') === $option)>{{ $option }}</option>@endforeach</select></label>
            @elseif($fieldType === 'radio' || $fieldType === 'checkbox')
                <fieldset class="fieldset" data-form-field="{{ $fieldKey }}"><legend>{{ $fieldLabel }} @if($fieldRequired)<span>*</span>@endif</legend><div class="field-options">@foreach($fieldOptions as $option)<label><input type="{{ $fieldType === 'radio' ? 'radio' : 'checkbox' }}" name="custom[{{ $fieldKey }}]{{ $fieldType === 'checkbox' ? '[]' : '' }}" value="{{ $option }}" @checked($fieldType === 'radio' ? old('custom.'.$fieldKey, $field['default_value'] ?? '') === $option : in_array($option, (array) old('custom.'.$fieldKey, []), true)) @required($fieldRequired && $loop->first)> {{ $option }}</label>@endforeach</div></fieldset>
            @else
                @php($inputType = in_array($fieldType, ['date', 'email', 'phone', 'number', 'quantity'], true) ? ($fieldType === 'phone' ? 'tel' : ($fieldType === 'quantity' ? 'number' : $fieldType)) : 'text')
                @if(in_array($fieldType, ['file', 'image'], true))
                    <label data-form-field="{{ $fieldKey }}">{{ $fieldLabel }} @if($fieldRequired)<span class="required-mark">{{ app()->getLocale() === 'ar' ? 'مطلوب' : 'Required' }}</span>@endif<input type="file" name="custom[{{ $fieldKey }}]" @if($fieldType === 'image')accept="image/*"@endif @required($fieldRequired)></label>
                @else
                    <label data-form-field="{{ $fieldKey }}">{{ $fieldLabel }} @if($fieldRequired)<span class="required-mark">{{ app()->getLocale() === 'ar' ? 'مطلوب' : 'Required' }}</span>@endif<input type="{{ $inputType }}" name="custom[{{ $fieldKey }}]" value="{{ old('custom.'.$fieldKey, $field['default_value'] ?? '') }}" placeholder="{{ $fieldPlaceholder }}" @required($fieldRequired)></label>
                @endif
            @endif
        @endforeach
        @if($errors->any())<div style="color:#b42318">{{ $errors->first() }}</div>@endif<button type="submit">{{ __('landivo.public.submit') }}</button>
    </form></section>@endif
    @php($footerHtml = app()->getLocale() === 'ar' ? data_get($landingPage->settings, 'footer_html_ar') : data_get($landingPage->settings, 'footer_html_en'))
    @php($footerStyle = data_get($landingPage->settings, 'footer_style', 'dark'))
    @php($footerAlignment = data_get($landingPage->settings, 'footer_alignment', 'center'))
    <style>.landing-footer{text-align:{{ $footerAlignment }};margin-top:{{ max(18, (int) data_get($landingPage->settings, 'footer_spacing', 28)) }}px;{{ $footerStyle === 'light' ? 'background:#ffffff;color:#172033;border:1px solid #e2e8f0;' : '' }}{{ $footerStyle === 'brand' ? 'background:linear-gradient(135deg,var(--brand),color-mix(in srgb,var(--brand) 70%,#172033));' : '' }}{{ $footerStyle === 'glass' ? 'background:color-mix(in srgb,var(--brand) 18%,#ffffff);color:#172033;border:1px solid color-mix(in srgb,var(--brand) 30%,#ffffff);backdrop-filter:blur(14px);' : '' }}</style>
    @if(filled($footerHtml) || filled(data_get($landingPage->settings, 'footer_html')))<footer class="landing-footer" style="order:100">{!! $footerHtml ?: data_get($landingPage->settings, 'footer_html') !!}</footer>@endif
    @if((bool) data_get($landingPage->settings, 'show_whatsapp_support') && filled(data_get($landingPage->settings, 'whatsapp_support_number')))
        @php($whatsappNumber = preg_replace('/\D+/', '', (string) data_get($landingPage->settings, 'whatsapp_support_number')))
        @php($whatsappMessage = data_get($landingPage->settings, 'whatsapp_support_message') ?: (app()->getLocale() === 'ar' ? 'مرحباً، أريد الاستفسار عن المنتج' : 'Hello, I would like to ask about the product'))
        <a class="floating-whatsapp" href="https://wa.me/{{ $whatsappNumber }}?text={{ rawurlencode($whatsappMessage) }}" target="_blank" rel="noopener" aria-label="WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3a8.8 8.8 0 0 0-7.6 13.4L3 21l4.8-1.3A8.8 8.8 0 1 0 12 3Zm4.7 12.6c-.2.5-1 .9-1.4.9-.4.1-.9.1-1.5-.1a12.4 12.4 0 0 1-1.4-.5 10.8 10.8 0 0 1-4.2-4.1c-.3-.5-.6-1.1-.6-1.7s.3-1.1.6-1.4c.2-.2.4-.3.6-.3h.4c.2 0 .3.1.4.4l.6 1.5c.1.2.1.4 0 .6l-.3.4c-.1.2-.2.3-.1.5.3.6.8 1.1 1.3 1.5.5.4 1.1.7 1.7.9.2.1.4 0 .5-.1l.6-.7c.1-.2.3-.2.5-.1l1.5.7c.2.1.3.2.3.5Z"/></svg></a>
    @endif
</main><script>document.querySelectorAll('[data-countdown]').forEach(function(el){var end=new Date(el.dataset.countdown).getTime();var tick=function(){var diff=Math.max(0,end-Date.now()),values={days:Math.floor(diff/86400000),hours:Math.floor(diff%86400000/3600000),minutes:Math.floor(diff%3600000/60000),seconds:Math.floor(diff%60000/1000)};Object.keys(values).forEach(function(unit){var node=el.querySelector('[data-unit="'+unit+'"]');if(node)node.textContent=String(values[unit]).padStart(2,'0')})};tick();setInterval(tick,1000)});</script>@if($showOrderForm)<script>var fieldConditions=@json($formFields->mapWithKeys(fn($field)=>[$field['internal_name']??$field['key']=>($field['conditions']??[])])->all());var readField=function(key){var nodes=document.querySelectorAll('[name="custom['+key+']"], [name="custom['+key+'][]"]'),checked=Array.from(nodes).filter(function(n){return n.checked}).map(function(n){return n.value});var node=nodes[0];return checked.length?checked:(node?node.value:'')};var updateFields=function(){Object.keys(fieldConditions).forEach(function(key){var conditions=fieldConditions[key]||[],visible=conditions.every(function(c){var actual=readField(c.field),expected=String(c.value||'');return c.operator==='not_equals'?String(actual)!==expected:c.operator==='contains'?(Array.isArray(actual)?actual.indexOf(expected)>=0:String(actual).indexOf(expected)>=0):String(actual)===expected});var wrapper=document.querySelector('[data-form-field="'+key+'"]');if(wrapper)wrapper.style.display=visible?'':'none'});};document.querySelectorAll('input[name^="custom["],select[name^="custom["],textarea[name^="custom["]').forEach(function(n){n.addEventListener('change',updateFields);n.addEventListener('input',updateFields)});updateFields();</script>@endif</body></html>
