<?php

declare(strict_types=1);

return [
    'navigation' => ['products' => 'المنتجات', 'landing_pages' => 'صفحات الهبوط', 'orders' => 'الطلبات', 'customers' => 'العملاء والطلبات المحتملة', 'order_statuses' => 'حالات الطلبات', 'reviews' => 'تقييمات الزوار'],
    'products' => ['singular' => 'منتج', 'plural' => 'المنتجات', 'create' => 'إضافة منتج', 'edit' => 'تعديل المنتج', 'sku' => 'رمز المنتج SKU', 'price' => 'السعر', 'compare_at_price' => 'السعر قبل الخصم', 'currency' => 'العملة', 'quantity' => 'الكمية', 'status' => 'الحالة', 'image' => 'الصورة الرئيسية', 'translations' => 'الترجمات', 'locale' => 'اللغة', 'name' => 'اسم المنتج', 'description' => 'الوصف'],
    'landing_pages' => ['singular' => 'صفحة هبوط', 'plural' => 'صفحات الهبوط', 'create' => 'إضافة صفحة هبوط', 'edit' => 'تعديل صفحة الهبوط', 'slug' => 'المعرّف المختصر', 'template' => 'القالب', 'product' => 'المنتج', 'status' => 'الحالة', 'default_locale' => 'اللغة الافتراضية', 'translations' => 'الترجمات', 'locale' => 'اللغة', 'title' => 'عنوان الصفحة', 'description' => 'وصف الصفحة', 'font_family' => 'نوع الخط', 'heading_size' => 'حجم العناوين', 'body_size' => 'حجم النص', 'primary_color' => 'اللون الأساسي'],
    'orders' => ['singular' => 'طلب', 'plural' => 'الطلبات', 'number' => 'رقم الطلب', 'customer' => 'العميل', 'status' => 'حالة الطلب', 'total' => 'الإجمالي', 'source' => 'المصدر', 'notes' => 'ملاحظات'],
    'customers' => ['singular' => 'عميل', 'plural' => 'العملاء والطلبات المحتملة', 'name' => 'الاسم', 'phone' => 'رقم الهاتف', 'email' => 'البريد الإلكتروني', 'city' => 'المدينة', 'country' => 'الدولة'],
    'order_statuses' => ['singular' => 'حالة طلب', 'plural' => 'حالات الطلبات', 'name_ar' => 'الاسم بالعربية', 'name_en' => 'الاسم بالإنجليزية', 'slug' => 'المعرّف', 'color' => 'اللون', 'sort_order' => 'الترتيب', 'is_active' => 'نشطة', 'is_final' => 'نهائية'],
    'reviews' => ['singular' => 'تقييم', 'plural' => 'تقييمات الزوار', 'name' => 'اسم الزائر', 'rating' => 'التقييم', 'landing_page' => 'صفحة الهبوط', 'product' => 'المنتج', 'content' => 'نص التقييم', 'photo' => 'صورة الزائر', 'approved' => 'معتمد', 'featured' => 'مميز', 'created_at' => 'تاريخ الإنشاء'],
    'statuses' => ['draft' => 'مسودة', 'active' => 'نشط', 'archived' => 'مؤرشف', 'published' => 'منشور', 'unpublished' => 'غير منشور'],
    'locales' => ['ar' => 'العربية', 'en' => 'الإنجليزية'],
    'actions' => ['create' => 'إضافة', 'save' => 'حفظ', 'cancel' => 'إلغاء', 'edit' => 'تعديل', 'delete' => 'حذف'],
    'dashboard' => ['heading' => 'الطلبات والأداء', 'total_leads' => 'إجمالي العملاء المحتملين', 'orders' => 'الطلبات', 'new_orders' => 'الطلبات الجديدة', 'revenue' => 'الإيرادات', 'landing_pages' => 'صفحات الهبوط', 'captured' => 'جميع العملاء المسجلين', 'submitted' => 'جميع الطلبات المرسلة', 'awaiting_contact' => 'بانتظار التواصل', 'order_value' => 'إجمالي قيمة الطلبات', 'created_pages' => 'الصفحات المنشأة'],
    'public' => ['order_title' => 'اطلب الآن', 'price_after_discount' => 'السعر بعد الخصم', 'price_before_discount' => 'السعر قبل الخصم', 'name' => 'الاسم', 'phone' => 'رقم الهاتف', 'quantity' => 'الكمية', 'city' => 'المدينة', 'submit' => 'إرسال الطلب', 'thank_you' => 'شكرًا لك، تم استلام طلبك', 'order_number' => 'رقم الطلب', 'back' => 'العودة إلى الصفحة', 'product_unavailable' => 'هذا المنتج غير متاح حاليًا.'],
    'sections' => ['hero' => 'البطاقة الرئيسية', 'product_gallery' => 'معرض المنتج', 'gallery' => 'معرض الصور', 'features' => 'المميزات', 'countdown' => 'العداد التنازلي', 'testimonials' => 'تقييمات العملاء', 'faq' => 'الأسئلة الشائعة', 'order_form' => 'نموذج الطلب', 'whatsapp' => 'زر واتساب', 'footer' => 'التذييل', 'video' => 'الفيديو', 'social_media' => 'التواصل الاجتماعي'],
    'editor' => ['basic' => 'المعلومات الأساسية', 'page_identity' => 'هوية الصفحة', 'page_identity_description' => 'حدد الرابط والمنتج وحالة النشر.', 'translations' => 'المحتوى واللغات', 'add_translation' => 'إضافة لغة', 'design' => 'التصميم', 'design_settings' => 'الهوية البصرية', 'design_description' => 'تحكم بالخطوط والأحجام واللون الأساسي.', 'visibility' => 'الظهور', 'show_price' => 'إظهار السعر', 'show_compare_price' => 'إظهار السعر السابق', 'show_order_form' => 'إظهار نموذج الطلب', 'price_settings' => 'مظهر الأسعار', 'price_description' => 'خصص لون وحجم السعر الحالي والسعر السابق بشكل مستقل.', 'current_price_color' => 'لون السعر الحالي', 'compare_price_color' => 'لون السعر السابق', 'current_price_size' => 'حجم السعر الحالي', 'compare_price_size' => 'حجم السعر السابق', 'sections' => 'أقسام الصفحة', 'page_sections' => 'منشئ الأقسام', 'sections_description' => 'أضف الأقسام ورتبها بالسحب والإفلات واضبط كل قسم بحقول مخصصة.', 'section_type' => 'نوع القسم', 'order' => 'الترتيب', 'visible' => 'ظاهر', 'section_title' => 'عنوان القسم', 'subtitle' => 'النص المساند', 'optional' => 'اختياري', 'ends_at' => 'ينتهي العرض في', 'countdown_style' => 'نمط العداد', 'countdown_cards' => 'خانات منفصلة', 'countdown_minimal' => 'بسيط', 'countdown_color' => 'لون أرقام العداد', 'countdown_label_color' => 'لون عناوين العداد', 'form_fields' => 'حقول نموذج الطلب', 'field_type' => 'نوع الحقل', 'field_label' => 'اسم الحقل', 'field_key' => 'مفتاح الحقل', 'placeholder' => 'النص الإرشادي', 'required' => 'إجباري', 'invoice' => 'يظهر في الفاتورة', 'options' => 'الخيارات', 'options_help' => 'اكتب خيارًا واحدًا في كل سطر.', 'add_field' => 'إضافة حقل', 'type_text' => 'نص قصير', 'type_textarea' => 'نص طويل', 'type_select' => 'قائمة منسدلة', 'type_radio' => 'اختيار واحد', 'type_checkbox' => 'اختيارات متعددة', 'type_date' => 'تاريخ', 'whatsapp_number' => 'رقم واتساب', 'button_label' => 'نص الزر', 'feature_one' => 'الميزة الأولى', 'feature_two' => 'الميزة الثانية', 'feature_three' => 'الميزة الثالثة', 'section_images' => 'صور القسم', 'video_url' => 'رابط الفيديو', 'add_section' => 'إضافة قسم'],
    'field_types' => ['text' => 'نص', 'email' => 'بريد إلكتروني', 'phone' => 'هاتف', 'number' => 'رقم', 'textarea' => 'نص طويل', 'select' => 'قائمة منسدلة', 'radio' => 'اختيار واحد', 'checkbox' => 'اختيارات متعددة', 'date' => 'تاريخ', 'hidden' => 'مخفي', 'quantity' => 'كمية', 'product_variant' => 'نسخة المنتج', 'address' => 'العنوان', 'city' => 'المدينة', 'country' => 'الدولة', 'file' => 'ملف', 'image' => 'صورة'],
    'field_builder' => ['default_value' => 'القيمة الافتراضية', 'validation_rules' => 'قواعد التحقق', 'conditions' => 'شروط الظهور', 'condition_field' => 'الحقل المرتبط', 'condition_operator' => 'عامل المقارنة', 'condition_value' => 'القيمة المطلوبة', 'add_condition' => 'إضافة شرط'],
    'thank_you' => ['mode' => 'وجهة ما بعد إرسال الطلب', 'internal' => 'صفحة شكر داخلية', 'external' => 'تحويل إلى رابط خارجي', 'title_ar' => 'عنوان الصفحة بالعربية', 'title_en' => 'عنوان الصفحة بالإنجليزية', 'message_ar' => 'التفاصيل بالعربية', 'message_en' => 'التفاصيل بالإنجليزية', 'button_ar' => 'نص الزر بالعربية', 'button_en' => 'نص الزر بالإنجليزية', 'countdown' => 'عدد ثواني العداد', 'redirect_url' => 'رابط التحويل', 'image_ar' => 'الصورة العربية', 'image_en' => 'الصورة الإنجليزية', 'head_code' => 'كود Head / Pixel', 'body_code' => 'كود Body / Pixel'],
    'seo' => ['title_ar' => 'عنوان SEO بالعربية', 'title_en' => 'عنوان SEO بالإنجليزية', 'description_ar' => 'وصف SEO بالعربية', 'description_en' => 'وصف SEO بالإنجليزية', 'keywords' => 'كلمات SEO', 'canonical' => 'الرابط الأساسي', 'noindex' => 'إخفاء الصفحة عن محركات البحث', 'product_image_ar' => 'صورة المنتج بالعربية', 'product_image_en' => 'صورة المنتج بالإنجليزية', 'head_code' => 'Head Code', 'body_code' => 'Body Code'],
    'builder' => ['media' => 'الصور والتواصل', 'slider' => 'سلايدر الصور', 'slider_description' => 'تحكم بصور السلايدر وطريقة تشغيله.', 'autoplay' => 'تشغيل تلقائي', 'interval' => 'الفاصل بين الصور بالميلي ثانية', 'link' => 'الرابط', 'color' => 'اللون', 'add_social' => 'إضافة رابط تواصل', 'title' => 'العنوان', 'button' => 'نص الزر', 'message' => 'الرسالة', 'order' => 'ترتيب الأقسام', 'order_description' => 'رتب أقسام صفحة الهبوط حسب الترتيب الذي سيظهر للزائر.', 'add_section_order' => 'إضافة قسم للترتيب'],
];
